### ISSUE TITLE
Receiving data from LMS4124

### ISSUE THREAD

**Issue by rpSICK** [SICKAG/ScanSegmentAPI#1]
Hello

I'm trying to receive data from LMS4124
I get the following errors:

- When using compact: "
CRC failed. Expected 2365587480, got 1705817130.
Failed to extract payload from data.
"

- When using msgpack: "
Actual length of payload and expected length do not match. Expected 2735538176 bytes, got 3488.
Failed to extract payload from data.
"

I can't configure the data format (compact or msgpack) for the LMS using telegram as far as I know (couldn't find reference on the docs).

So my questions:
Is this API compatible to work with LMS devices?
If so what should I change?
If not, do I need to make my own data parser or just wait for the next version?

Thank you
Rotem

**Comment by weinmalSICKAG** [comment]
Hello,
this API is compatible with the MultiScan and the PicoScan devices.
Currently we do not plan to support LMS devices in this API.
You will need to write your own parser.

Best
weinmal
